include:
  - rabbitMQ/docker-compose.yaml
  - inventory-service/docker-compose.yaml
  - order-service/docker-compose.yaml
  - product-service/docker-compose.yaml
  - ApiGateway/docker-compose.yaml
  - monitoring/docker-compose.yaml
networks:
  ecommerce-network:
    driver: overlay

services:
  order-service:
    build: ./order-service
    depends_on:
      - mysql_order
      - inventory-service
    
  api-gateway:
    depends_on:
      - order-service
      - inventory-service
      - product-service