worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    resolver 127.0.0.11 valid=5s; 

    upstream product-cluster {
        hash $http_x_test_ip consistent; 
        server tasks.product-service:8080;
    }
    
    upstream order-cluster {
        hash $http_x_test_ip consistent;
        server tasks.order-service:8081;
    }
    
    upstream inventory-cluster {
        hash $http_x_test_ip consistent;
        server tasks.inventory-service:8082;
    }

    server {
        listen       80;
        server_name  localhost;

        location /api/product {
            set $upstream_product product-cluster; 
            proxy_pass http://$upstream_product;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            add_header X-Handled-By $upstream_addr always;
        }

        location /api/order {
            set $upstream_order order-cluster;
            proxy_pass http://$upstream_order;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            add_header X-Handled-By $upstream_addr always;
        }

        location /api/inventory {
            set $upstream_inventory inventory-cluster;
            proxy_pass http://$upstream_inventory;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            add_header X-Handled-By $upstream_addr always;
        }
    }
}