services:
  mysql_order:
    image: mysql:8.3.0
    container_name: mysql_order
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - ecommerce-network
  order-service:
    build: .
    depends_on:
      - mysql_order
      - inventory-service
    environment:
    - MYSQL_HOST=mysql_order
    - MYSQL_PORT=3306
    - SPRING_DATASOURCE_USERNAME=${DB_USER}
    - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
    - INVENTORY_URL=http://inventory-service:8082
    deploy: 
      replicas: 3
      endpoint_mode: dnsrr
    networks:
      - ecommerce-network
networks:
  ecommerce-network:
